In [ ]:
import numpy as np

In [ ]:
ar1 = np.array([1,2,3])
ar1

In [7]:
print(np.zeros((2,3)))
print(np.ones((2,2)))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.eye(3))
print(np.random.rand(2,2))
print(np.random.randint(1,10,size=(2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.11688246 0.42698464]
 [0.53144236 0.77078893]]
[[1 2 8]
 [7 9 7]]


In [9]:
ar = np.arange(10, 30)
print(ar[ar%2==0])
print(np.random.randint(1,10))

[10 12 14 16 18 20 22 24 26 28]
2


In [14]:
mat = np.array([[1, 2, 3, 40],
                [5, 5, 6, 70],
                [7, 8, 9, 0]])
ar = mat[::-1,:]
ar

array([[ 7,  8,  9,  0],
       [ 5,  5,  6, 70],
       [ 1,  2,  3, 40]])

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
a

[5 7 9]
[ 4 10 18]


array([1, 2, 3])

In [ ]:
arr = np.arange(1,7)
ar = arr.reshape((3,2))
ar.resize()
ar

In [15]:
a = np.array([1,2,3])
b = np.array([[1],[2]])
print(a + b)
b

[[2 3 4]
 [3 4 5]]


array([[1],
       [2]])

In [17]:
arr = np.array([0, np.pi/2, np.pi])
print((arr))
print(np.log(np.array([1, np.e, np.e**2])))



[0.         1.57079633 3.14159265]
[0. 1. 2.]


In [ ]:
arr = np.array([10, np.pi/2, np.pi])
print(np.sin(arr))
print(np.log(np.array([1, np.e, np.e**2])))
arr


In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.vstack((a, b)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
a = np.array([[1, 2, 3, 80], [4, 5, 6, 70]])
a[:2, ::-1]

array([[80,  3,  2,  1],
       [70,  6,  5,  4]])

In [46]:
#1
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
#2
row1 = a[0:1, ]
col2 = a[:, :2]
print(row1)
print(col2)
#3
iden = np.eye(4)
#4
a=np.array([1,2,3])
b=np.array([4,5,6])
print((a+b))
print(b - 1)
print(a * b)

[[1 2 3]]
[[1 2]
 [4 5]
 [7 8]]
[5 7 9]
[3 4 5]
[ 4 10 18]


In [49]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.reshape((1,6)))
print(a.flatten())  # [1 2 3 4 5 6]


[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


In [55]:
print(np.random.seed(1))             # For reproducibility
print(np.random.rand(2, 2))           # Random floats [0,1)
print(np.random.randn(2, 2))            # Normal distribution
print(np.random.randint(1, 10, (2, 2)))   # Random ints


None
[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
[[-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]]
[[6 3]
 [5 3]]


In [56]:
large_sample = np.random.randn(1000000)
print("Approx. Mean:", large_sample.mean())
print("Approx. Std Dev:", large_sample.std())

Approx. Mean: 0.0012247657293582475
Approx. Std Dev: 0.9991881251827761


In [63]:
ar1 = np.random.randint(low=0, high=100, size=12)
ar2 = np.random.randint(low=0, high=100, size=12)
print(ar1.reshape(3,4))
print(np.hstack((ar1, ar2)))
print(np.vstack((ar1, ar2)))

[[33 79 31 68]
 [29 28 33 70]
 [22 34 14 80]]
[33 79 31 68 29 28 33 70 22 34 14 80 47 57 62 34 96 90  0 81 91 59 83 25]
[[33 79 31 68 29 28 33 70 22 34 14 80]
 [47 57 62 34 96 90  0 81 91 59 83 25]]


In [67]:
ar = np.random.randint(0, 20, (5,5))
print(ar)
print(ar[ar>10])

[[ 0  3  9  2  7]
 [ 2  4 10  7 16]
 [18 13  9  5 16]
 [ 3 15  4  1  0]
 [15 18  4  5  7]]
[16 18 13 16 15 15 18]


In [69]:
a = np.array([1, 2, 3])
b = 2
print(a + b)  # [3 4 5] → b is broadcasted to [2 2 2]

[3 4 5]


In [74]:
a  = np.array([1,1,1])
b=np.array([[2,2,2],[3,3,3],[4,4,4]])
result = a+b
print(result)

[[3 3 3]
 [4 4 4]
 [5 5 5]]


In [80]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [99]:
import time

a = np.arange(1e6)
start = time.time()
a = a * 2
print("NumPy time:", time.time() - start)

start = time.time()
a = []
for i in range (1000000):
    a.append(i)
print("noraml time = ", time.time() - start)


NumPy time: 0.003742694854736328
noraml time =  0.09804224967956543


In [104]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])


In [107]:
print(f"a.b\n{np.dot(a,b)}\n\nInverse of a\n{np.linalg.inv(a)}\n\n")
print(f"Determinant of a\n{np.linalg.det(a)}\n\n")
evalues, evectors = np.linalg.eig(a)
print(f"Eigen values {evalues}\n\neigenvetor of a\n{evectors}")

a.b
[[ 4  4]
 [10  8]]

Inverse of a
[[-2.   1. ]
 [ 1.5 -0.5]]


Determinant of a
-2.0000000000000004


Eigen values [-0.37228132  5.37228132]

eigenvetor of a
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [127]:
a = np.array([0,1,2])
b = np.array([1,2,3])
c = np.random.randint(0, 101, (5,4))
print(c)
print(c[a, b])

[[18 30 13  7]
 [ 1 89 17 13]
 [52 88 11  4]
 [13 29 67 78]
 [21 82 12 83]]
[30 17  4]


In [133]:
a = np.array([0,1,2])
b = np.array([1,2,3])
c = np.outer(a, b)
d = np.dot(a, b)
print(c)
print("d\n", d)
rows, cols = c.shape
print(f"rows = {rows}, col = {cols}")

[[0 0 0]
 [1 2 3]
 [2 4 6]]
d
 8
rows = 3, col = 3


In [169]:
#3
a = np.random.randint(1, 11, (3, 3))
print(a)
print("Determinat = ",np.linalg.det(a))
print("Inverse = \n", np.linalg.inv(a))

[[ 3  9  4]
 [ 8  6  8]
 [ 8  7 10]]
Determinat =  -99.99999999999996
Inverse = 
 [[-0.04  0.62 -0.48]
 [ 0.16  0.02 -0.08]
 [-0.08 -0.51  0.54]]
